### ISSUE TITLE
Mac OSX Run Fail

### ISSUE THREAD

**Issue by aiddenkeli** [lgandx/PCredz#10]
I get this when trying to run './Pcredz -i en1':
Traceback (most recent call last):
  File "./Pcredz", line 681, in <module>
    Run()
  File "./Pcredz", line 676, in Run
    decode_file(fname,'')
  File "./Pcredz", line 584, in decode_file
    p = pcap.pcapObject()
AttributeError: 'module' object has no attribute 'pcapObject'

I followed the install instructions by downloading the pylib package referenced, untar-ing it, and python setup.py installing it.

**Comment by lgandx** [comment]
Can't reproduce here, just fresh install everything and worked without issues.
Are you sure pypcap is not installed on your machine? If it is, please remove it and reinstall pylibpcap.
