### ISSUE TITLE
pcredz tries to write log file in /usr/sbin

### ISSUE THREAD

**Issue by bduncan** [lgandx/PCredz#11]
pcredz is writing a log file in /usr/sbin. It should log it somewhere else, like /var/log, use syslog, or logging to a file should be an option, since it seems to write the same data to stdout and to the log file. 

bduncan@ltw3701:~$ pcredz -i eth0
Pcredz 0.9
Author: Laurent Gaffie
Please send bugs/comments/pcaps to: lgaffie@trustwave.com
This script will extract NTLM (http,ldap,smb,sql,etc), Kerberos,
FTP, HTTP Basic and credit card data from a given pcap file or from a live interface.

Traceback (most recent call last):
  File "/usr/sbin/pcredz", line 81, in <module>
    l.addHandler(logging.FileHandler(Filename,'a'))
  File "/usr/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 936, in _open                                                                                                                         
    stream = open(self.baseFilename, self.mode)                                                                                                                                             
IOError: [Errno 13] Permission denied: '/usr/sbin/CredentialDump-Session.log'                                                                                                               
:( 1 bduncan@ltw3701:~$

Thanks,
Bruce

**Comment by lgandx** [comment]
This seems to be a permission problem, Pcredz should run as root when listening on an interface.
What distribution & package are you using?

**Comment by bduncan** [comment]
This is on kubuntu 15.04, package version 0.9-1.
The permissions are not a problem. If I run sudo pcredz it happily creates `/usr/sbin/CredentialDump-Session.log`, which is the wrong place for a log file.

**Comment by lgandx** [comment]
Was it installed via apt-get (it's in debian&ubuntu repos)?
Usually, Pcredz needs to be run from the running directory, but if it was installed in /usr/bin, then the log file will be located there.

**Comment by bduncan** [comment]
Yes, installed using apt-get.
Pcredz needs to write its log file somewhere else so that it can be run by normal users. The easiest option is probably not to create a log file at all, since it already sends the same data to stderr. Logging to stderr is better, since the user can decide where to put the log file themselves.

**Comment by lgandx** [comment]
Pcredz writes the log file in the current directory. You're supposed to download it from source, not via a distribution package. If you're using the deb file then request the feature to the deb rep maintainer, else download it from here and run it from the PCredz dir.
