### ISSUE TITLE
issue in live capture!

### ISSUE THREAD

**Issue by Indeserpen** [lgandx/PCredz#15]
Hello, system i am using kali linux 2.0 amd64:
root@kali:~/PCredz# apt-get remove python-pypcap && apt-get install python-libpcap
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Package 'python-pypcap' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree  
Reading state information... Done
python-libpcap is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

When I run it 
root@kali:~/PCredz# ./Pcredz -i wlan0
Pcredz 1.0.0
Author: Laurent Gaffie
Please send bugs/comments/pcaps to: lgaffie@trustwave.com
This script will extract NTLM (http,ldap,smb,sql,etc), Kerberos,
FTP, HTTP Basic and credit card data from a given pcap file or from a live interface.

CC number scanning activated

Traceback (most recent call last):
  File "./Pcredz", line 681, in <module>
    Run()
  File "./Pcredz", line 676, in Run
    decode_file(fname,'')
  File "./Pcredz", line 584, in decode_file
    p = pcap.pcapObject()
AttributeError: 'module' object has no attribute 'pcapObject!!!

Thanks

**Comment by ubermedina** [comment]
This is still an issue for me when running the latest update. I am seeing the exact same error message posted by @Indeserpen .

./Pcredz -i wlan0 -t -v -c
Pcredz 1.0.0
Author: Laurent Gaffie
Please send bugs/comments/pcaps to: laurent.gaffie@gmail.com
This script will extract NTLM (http,ldap,smb,sql,etc), Kerberos,
FTP, HTTP Basic and credit card data from a given pcap file or from a live interface.

CC number scanning is deactivated

Traceback (most recent call last):
  File "./Pcredz", line 757, in <module>
    Run()
  File "./Pcredz", line 750, in Run
    decode_file(fname,'')
  File "./Pcredz", line 651, in decode_file
    p = pcap.pcapObject()
AttributeError: 'module' object has no attribute 'pcapObject'

**Comment by omriman067** [comment]
was there ever any solution found?

**Comment by ad0nis** [comment]
./Pcredz -i eth0
Pcredz 1.0.0
Author: Laurent Gaffie
Please send bugs/comments/pcaps to: laurent.gaffie@gmail.com
This script will extract NTLM (http,ldap,smb,sql,etc), Kerberos,
FTP, HTTP Basic and credit card data from a given pcap file or from a live interface.

CC number scanning activated

Traceback (most recent call last):
  File "./Pcredz", line 757, in <module>
    Run()
  File "./Pcredz", line 750, in Run
    decode_file(fname,'')
  File "./Pcredz", line 651, in decode_file
    p = pcap.pcapObject()
AttributeError: 'module' object has no attribute 'pcapObject'
