### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by mboelen** [lgandx/PCredz#19]
We are [reviewing](https://linuxsecurity.expert/tools/pcredz/) your tool and had some challenges finding the license. Can you put up a license file?

**Comment by Zamanry** [comment]
Bumping this too, my employer would like to use your code as a part of our penetration tests. Not to distribute, but use. Could you add an appropriate license to allow this OR at least provide a license to clarify your software usage? Thanks!

**Comment by lgandx** [comment]
Fixed with the latest commit.

Thanks
