### ISSUE TITLE
AttributeError: 'module' object has no attribute 'pcapObject'

### ISSUE THREAD

**Issue by KeepItMeke** [lgandx/PCredz#28]
Hi there, 
I have recently been seeing an issue I am having trouble resolving when running PCredz:

Traceback (most recent call last):
  File "./Pcredz", line 757, in <module>
    Run()
  File "./Pcredz", line 750, in Run
    decode_file(fname,'')
  File "./Pcredz", line 651, in decode_file
    p = pcap.pcapObject()
AttributeError: 'module' object has no attribute 'pcapObject'

I have pylibpcap installed and have removed libpcap has i understand they don't play well together?:
Requirement already satisfied: pylibpcap in /usr/local/lib/python2.7/dist-packages (0.6.4)

Any assistance is appreciated whilst I figure this one out

**Comment by lgandx** [comment]
Hi, 
Are you running Pcredz on a Kali distribution?

**Comment by KeepItMeke** [comment]
This is correct, I have since updated kali, with a fresh install 
user@computer:~/tools/PCredz$ ./Pcredz 
libpcap not installed.
try : apt-get remove python-pypcap && apt-get install python-libpcap

which results in:
Package python-libpcap is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by lgandx** [comment]
Unfortunately, Kali is not supported. Please submit a bug on their bug tracker.
Cheers
