### ISSUE TITLE
python-libpcap deprecated

### ISSUE THREAD

**Issue by tickTackHack** [lgandx/PCredz#30]
On the latest Kali build, apt is reporting that python-libpcap does not exist.  Also attempts to install it from the sourceforge link provided by the error message when trying to run PCredz fails. Is there an alternative or can PCredz be updated to use another pcap parsing library?

**Comment by gregsec** [comment]
The following should fix it for you.

wget http://mirrors.kernel.org/ubuntu/pool/universe/p/python-libpcap/python-libpcap_0.6.4-1_amd64.deb && dpkg -i python-libpcap_0.6.4-1_amd64.deb

**Comment by tickTackHack** [comment]
That does it. Thanks!

**Comment by Clutchisback1** [comment]
Had this too...this fixed my issue as well...Care to update the Readme.md? Would have saved me and others some time for sure. Great tool though...Thanks

**Comment by lgandx** [comment]
Good point, just updated the Readme file.
