### ISSUE TITLE
Lack of IPv6 support

### ISSUE THREAD

**Issue by bert128** [lgandx/PCredz#33]
PCredz does not support IPv6 traffic, and will silently ignore any that's present on the interface or in any imported pcap files.

On an IPv6-only or dual stack network, modern operating systems will use IPv6 in preference to any legacy protocols, so all legitimate traffic would be using this protocol.

This occurs because the Print_Packet_* functions explicitly check for the legacy IPv4 ether type (0x0800) and ignore anything else:

`       	if data[12:14]== b'\x08\x00':
`

This is then passed to the function Decode_Ip_Packet which extracts the src/destination address from the packet header. It then returns the packet payload  (ie starting from TCP/UDP header).

The attached patch also checks for the IPv6 ether type (0x86dd) and passes it to a separate function Decode_Ipv6_Packet that handles an IPv6 header. The higher level TCP/UDP payloads remain the same on IPv6 so execution continues after parsing the header and returning the correct start of the payload.

So far this only works with a standard 40 byte IPv6 header, it does not properly check the next-header field so it would fail if there are optional extension headers present (rare).

Instead of using a separate function for IPv6, it may be preferable to use a single function and then check the version field of the header and act accordingly.

[v6.txt](https://github.com/lgandx/PCredz/files/5492537/v6.txt)

**Comment by lgandx** [comment]
Hi, 
Thank for submitting this issue. I need to modify some code to make it work, but this will be implemented today :)
Cheers,

**Comment by lgandx** [comment]
Changes have been pushed. 
Thanks!
