### ISSUE TITLE
Support for SMTP NTLM hash

### ISSUE THREAD

**Issue by JBalanza** [lgandx/PCredz#34]
Hi,

I wonder if NTLM hashes for SMTP authentication could be supported by PCredz. If so, I have some research done over your tool using your function "ParseNTLMHash". It works manually perfectly but I didn't automatize it within the tool pcap analysis. NTLM authentication is widely used by SMTP and I think it would be interesting. This feature requires very low R&D since all needed is already developed and is very similar to HTTP NTLM authentication that you've already support for it.

Please let me know if you want me to help to develop the feature or PR.

Regards.

**Comment by lgandx** [comment]
Hi, 
Pcredz should pick it up since it inspects all packets for NTLM exchanges (for RPC auth, HTTP on non common ports, etc).
Thanks
