### ISSUE TITLE
python dependencies not met but are. Maybe i am tired but what?

### ISSUE THREAD

**Issue by TheBlindHacker** [lgandx/PCredz#38]
└─$ sudo python3 ./Pcredz -i eth0 -v
libpcap not installed.
try : apt install python3-pip && pip3 install Cython && pip3 install python-libpcap

└─$ sudo apt install python3-pip && pip3 install Cython && pip3 install python-libpcap
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (20.3.4-1).
The following packages were automatically installed and are no longer required:
  libxml-dom-perl libxml-perl libxml-regexp-perl
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1478 not upgraded.
Requirement already satisfied: Cython in /usr/lib/python3/dist-packages (0.29.21)
Requirement already satisfied: python-libpcap in /home/pentester/.local/lib/python3.8/site-packages (0.4.0)
Requirement already satisfied: Cython>=0.29.13 in /usr/lib/python3/dist-packages (from python-libpcap) (0.29.21)

**Comment by lgandx** [comment]
This issue has been resolved. Let me know if you experience any other issues.

**Comment by TheBlindHacker** [comment]
WIll pull and retry thanks friend!
