### ISSUE TITLE
Enhancement: Read from sys.stdin

### ISSUE THREAD

**Issue by windgmbh** [lgandx/PCredz#40]
# Proposed Enhancement
It would be great if the program could read from `sys.stdin`. That way it would be possible to pipe tcpdump streams directly into the program.

# Example
This way you could do for example
```$ tcpdump '<capture filter>' -U -w - | Pcredz | grep -i found > found_creds.log```
or even
``` ssh root@remote-server "(tcpdump '<capture filter>' -U -w -)" | Pcredz | grep -i found > found_creds.log```

# Benefits
It would be possible to process a huge amount of traffic without requiring to store large amounts of pcap data.

**Comment by lgandx** [comment]
Sorry for the delay on this. 
Pcredz already offers live capture, best would be to run python3 Pcredz -i eth0 -v instead.

**Comment by AdrianVollmer** [comment]
I think there is still a use case for reading a stream, like if you can't run Pcredz on the remote machine.

However, this can also easily be done with bash process substitution:

```
Pcredz -f <(ssh root@remote-server "(tcpdump '<capture filter>' -U -w -)" )
```

**Comment by Nag1bat0r** [comment]
**sudo python3 ./PCredz.py -i eno1 -c -vv**


Traceback (most recent call last):
  File "/home/***/./PCredz.py", line 808, in <module>
    Run()
  File "/home/***/./PCredz.py", line 803, in Run
    decode_file(fname,'')
  File "/home/***/./PCredz.py", line 717, in decode_file
    Print_Packet_Tcpdump(plen, t, buf)
  File "/home/***/./PCredz.py", line 691, in Print_Packet_Tcpdump
    ParseDataRegex(decoded, SrcPort, DstPort)
  File "/home/***/./PCredz.py", line 446, in ParseDataRegex
    if DstPort == 88 and protocols[decoded['protocol']] == 'tcp':
KeyError: 89


Help pls
