### ISSUE TITLE
Error : libpcap not installed

### ISSUE THREAD

**Issue by s23hck** [lgandx/PCredz#41]
Hi, i have an issue with PCredz, When running:
`python3 ./Pcredz -f test.pcapng`

Got this:
`libpcap not installed.
try : apt install python3-pip && sudo apt-get install libpcap-dev && pip3 install Cython && pip3 install python-libpcap`

also, requirements are installed : 
`└─$ sudo apt install python3-pip && sudo apt-get install libpcap-dev && pip3 install Cython && pip3 install python-libpcap

Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
python3-pip est déjà la version la plus récente (20.3.4-4).

0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
libpcap-dev est déjà la version la plus récente (1.10.1-3).

0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
**Requirement already satisfied: Cython in /usr/lib/python3/dist-packages (0.29.21)
Requirement already satisfied: python-libpcap in /home/steph/.local/lib/python3.9/site-packages (0.4.0)
Requirement already satisfied: Cython>=0.29.13 in /usr/lib/python3/dist-packages (from python-libpcap) (0.29.21)**`

OS Information:
VERSION="2021.3"
VERSION_ID="2021.3"
VERSION_CODENAME="kali-rolling"
KERNEL: Linux 5.10.0-kali9-amd64
ARCHITECTURE: x86-64

How can i fix this ?

**Comment by lgandx** [comment]
Unfortunately I do not support Kali issues because the tools are modified/adapted to work on their distribution.
At this point you have two choice;
1) use Kali Pcredz package.
2) run a conventional linux and install the tools you need.
