### ISSUE TITLE
python-libpcap PyGen_Send Python 3.10 Deprecation

### ISSUE THREAD

**Issue by Zamanry** [lgandx/PCredz#47]
Using Python 3.10, I was unable to run PCredz. It appears that `PyGen_Send` is deprecated by `python-libpcap`. I ran PCredz just fine with Python 3.9, but not 3.10. I've only found a workaround by calling Python 3.9 directly.

**Error:**
![image](https://user-images.githubusercontent.com/28152647/167460311-7489697e-458a-4fcb-b3c9-c2a092ed1c99.png)

**Supplemental Information:**
![image](https://user-images.githubusercontent.com/28152647/167460420-a1148049-2567-46a5-8821-35a78b52e186.png)

If you need more information, I can give you what I can after sanitizing the output.

**Comment by lgandx** [comment]
see: https://github.com/lgandx/PCredz/issues/48#issuecomment-1183750043
