### ISSUE TITLE
libpcap Not Installed

### ISSUE THREAD

**Issue by Zamanry** [lgandx/PCredz#48]
I am trying to test #47 on a not Kali box, but I cannot get PCredz to even run due to it claiming libpcap is not installed. I attempted previous closed issue fixes, but couldn't get anything to work. I downloaded this Ubuntu image today and updated it.

![image](https://user-images.githubusercontent.com/28152647/168401837-f52ef945-afab-496a-9417-eeb7ab4e5d0c.png)

Let me know if you have any ideas or want me to retest.

**Comment by globo17** [comment]
Hi, were you able to fix this issue?

**Comment by Zamanry** [comment]
I attempted many different methods, but I was unable to locate a fix. I did not dive deep into PCredz source code or the various required dependencies.

**Comment by lgandx** [comment]
You're running pip with sudo. Try without sudo.

**Comment by Zamanry** [comment]
I tried and no luck on Ubuntu. I tried it again on Kali this time and I couldn't even install libpcap-dev there. Issue created there https://github.com/caizhengxin/python-libpcap/issues/14

**Comment by Zamanry** [comment]
> I tried and no luck on Ubuntu. I tried it again on Kali this time and I couldn't even install libpcap-dev there. Issue created there [caizhengxin/python-libpcap#14](https://github.com/caizhengxin/python-libpcap/issues/14)

This issue was unrelated. Python 3.9 PCredz is working with the above issue's resolution. However, Python 3.10 is not working on Kali or Ubuntu fresh fully up-to-date images. Sudo or no sudo. Same error.

I made sure `python3-dev`. `python3.10-dev`, `libpython3-dev`, and `libpython3.10-dev` were installed per this link: https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by lgandx** [comment]
This is a python3.10 with Cython issue.
Install python3.9, and download Cython source ( https://github.com/cython/cython ) and install it : 
`python3.9 setup.py build && python3.9 setup.py install`
Download libpcap: https://github.com/caizhengxin/python-libpcap
`python3.9 setup.py build && python3.9 setup.py install`

Pcredz will work again.

**Comment by linuxkd** [comment]
> This is a python3.10 with Cython issue. Install python3.9, and download Cython source ( https://github.com/cython/cython ) and install it : `python3.9 setup.py build && python3.9 setup.py install` Download libpcap: https://github.com/caizhengxin/python-libpcap `python3.9 setup.py build && python3.9 setup.py install`
> 
> Pcredz will work again.

Hey Laurent, I have walked through all the challenges with getting this to run properly on Python 3.10 and created an upstream issue for the folks responsible for python-libpcap. You can see the details here:
https://github.com/caizhengxin/python-libpcap/issues/16

I figured it would be worth letting you and others know via this issue. Nothing needs to be done on your end for the resolution.

<3 from SwAG

**Comment by Zamanry** [comment]
So my team has gotten PCredz to work now again on 3.9 or 3.10 doing:
```
sudo apt install libpcap-dev -y
python -m pip install cython --upgrade
python -m pip install python-libpcap --upgrade
```
You can't combine the pip commands together. Maybe we could modify the help command to say `--upgrade` on both pip tools to more clearly fix this issue?

**Comment by mjbear** [comment]
@Zamanry
If this is resolved (which is seems to be), could you resolve this issue thread?
